-- create

INSERT INTO `region` (`titleUz`, `titleRu`, `descUz`, `descRu`, `image`, `teacherImg`, `titleTeacherUz`, `titleTeacherRu`, `descTeacherUz`, `descTeacherRu`, `teacherLocation`)
VALUES
('Андижан', 'Andijan', 'Описание Андижанской области на узбекском', 'Description of Andijan in English', 'https://www.agro.uz/wp-content/uploads/2021/09/andijon-e1633416272681.jpg', 'учитель_андижан.jpg', 'Учитель из Андижанской области', 'Teacher from Andijan', 'Дополнительное описание учителя из Андижанской области на узбекском', 'Additional description of the teacher from Andijan in English', ""),
('Бухар', 'Bukhara', 'Описание Бухарской области на узбекском', 'Description of Bukhara in English', 'https://www.tatar-inform.ru/resize/shd/images/uploads/news/2023/9/1/32e83d3ee8a94eb9c9ae528bc4bb9a67.jpg', 'учитель_бухара.jpg', 'Учитель из Бухарской области', 'Teacher from Bukhara', 'Дополнительное описание учителя из Бухарской области на узбекском', 'Additional description of the teacher from Bukhara in English', ""),
('Ферган', 'Fergana', 'Описание Ферганской области на узбекском', 'Description of Fergana in English', 'https://dolorestravel.com/uploads/Guide/68/6272f4efb307c.jpg', 'учитель_фергана.jpg', 'Учитель из Ферганской области', 'Teacher from Fergana', 'Дополнительное описание учителя из Ферганской области на узбекском', 'Additional description of the teacher from Fergana in English', ""),
('Хорезм', 'Khorezm', 'Описание Хорезмской области на узбекском', 'Description of Khorezm in English', 'https://storage.kun.uz/source/6/KkQiU-ihPbO7x3vpTS18bfYEXNQNEIDK.jpg', 'ustoz rasmi', 'Учитель из Хорезмской области', 'Teacher from Khorezm', 'Дополнительное описание учителя из Хорезмской области на узбекском', 'Additional description of the teacher from Khorezm in English', ""),
('Наманган', 'Namangan', 'Описание Наманганской области на узбекском', 'Description of Namangan in English', 'https://central-asia.guide/wp-content/uploads/2022/03/Namangan-park-1024x682.jpg', 'ustoz rasmi', 'Учитель из Наманганской области', 'Teacher from Namangan', 'Дополнительное описание учителя из Наманганской области на узбекском', 'Additional description of the teacher from Namangan in English', ""),
('Навоий', 'Navoiy', 'Описание Навоийской области на узбекском', 'Description of Navoiy in English', 'https://uzbekistan.travel/storage/app/media/nargiza/cropped-images/cropped-images/Nurata_town-0-0-0-0-1583233278-0-0-0-0-1583233325.jpg', 'учитель_навои.jpg', 'Учитель из Навоийской области', 'Teacher from Navoiy', 'Дополнительное описание учителя из Навоийской области на узбекском', 'Additional description of the teacher from Navoiy in English', ""),
('Самарканд', 'Samarkand', 'Описание Самаркандской области на узбекском', 'Description of Samarkand in English', 'https://media.tacdn.com/media/attractions-content--1x-1/12/28/b4/46.jpg', 'учитель_самарканд.jpg', 'Учитель из Самаркандской области', 'Teacher from Samarkand', 'Дополнительное описание учителя из Самаркандской области на узбекском', 'Additional description of the teacher from Samarkand in English', ""),
('Сурхандаря', 'Surxondaryo', 'Описание Сурхандарьинской области на узбекском', 'Description of Surxondaryo in English', 'https://china-uz-friendship.com/wp-content/uploads/2019/10/image0104.jpg', 'учитель_сурхандарья.jpg', 'Учитель из Сурхандарьинской области', 'Teacher from Surxondaryo', 'Дополнительное описание учителя из Сурхандарьинской области на узбекском', 'Additional description of the teacher from Surxondaryo in English', ""),
('Сырдаря', 'Sirdaryo', 'Описание Сырдарьинской области на узбекском', 'Description of Sirdaryo in English', 'https://uzbekistan.travel/storage/app/media/nargiza/cropped-images/6-0-0-0-0-1583469510.jpg', 'учитель_сырдарья.jpg', 'Учитель из Сырдарьинской области', 'Teacher from Sirdaryo', 'Дополнительное описание учителя из Сырдарьинской области на узбекском', 'Additional description of the teacher from Sirdaryo in English', ""),
('Ташкент', 'Tashkent', 'Описание Ташкентской области на узбекском', 'Description of Tashkent in English', 'https://upload.wikimedia.org/wikipedia/commons/3/33/Tashkent_skyline_2019.jpg', 'учитель_ташкент.jpg', 'Учитель из Ташкентской области', 'Teacher from Tashkent', 'Дополнительное описание учителя из Ташкентской области на узбекском', 'Additional description of the teacher from Tashkent in English', "");

